---
# set to true for platforms that are provided by Toradex
standard: true
# descriptive information
name: .NET core 3.1 arm32v7 buster
version: "1.0"
description: Platform for console applications using .NET core 3.1 for arm32v7 on debian-buster
# supported modules (using product id),* means all modules except unsupported ones
supportedmodels: ["*"]
unsupportedmodels: []
# defines base image and dockerfile templates for the containers
baseimage:
  common:
    - torizon/arm32v7-debian-dotnet
    - buster
  debug:
  release:
# names of dockerfile templates
container:
  common:
  debug: debug.dockerfile
  release: release.dockerfile
# defines what languages/runtimes are supported by this platform
runtimes:
  - dotnet
tags: []

# information about how containers should run
ports:
  common: {}
  debug: { "2222/tcp": null }
  release: {}
volumes:
  common: {}
  debug: {}
  release: {}
devices:
  common: []
  debug: []
  release: []
privileged: false
extraparms:
  common: {}
  debug: {}
  release: {}
# information about the SDK (if required)
usesdk: false

usesysroot: false
# base image for the container/template
sdkbaseimage:
  common:
  debug:
  release:
# template file for SDK container build
sdkcontainer:
  common: null
  debug: null
  release: null

# additional platform-specific properties that can be used in projects or plugins
props:
  common: { "runtimeid": "linux-arm" }
  debug: {}
  release: {}
# additional scripts (docker-compose or shell) that can be used to start/stop
# the container
# If you use docker-compose file the application container should NOT be listed in the services, since it will be started by the debugger
dockercomposefile:
  common: null
  debug: null
  release: null
startupscript:
  common: null
  debug: null
  release: null
shutdownscript:
  common: null
  debug: null
  release: null
networks:
  common: []
  debug: []
  release: []
deprecated: true
